-- 일일로그 초기 스키마 (CLAUDE.md 6장)

CREATE TABLE member
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   VARCHAR(255) NOT NULL,
    password                VARCHAR(255) NOT NULL,
    name                    VARCHAR(50)  NOT NULL,
    -- TODO(D-16): 닉네임 길이 확정 시 조정. 검증은 MemberPolicy 상수로 제한한다.
    nickname                VARCHAR(50)  NOT NULL,
    password_reset_required BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ  NOT NULL,
    updated_at              TIMESTAMPTZ,
    deleted_at              TIMESTAMPTZ
);

-- TODO(D-11): 탈퇴 이메일 재가입 정책 확정 시 조정. [잠정] 활성 회원 기준 유니크
CREATE UNIQUE INDEX uk_member_email_active ON member (email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_member_nickname ON member (nickname);

CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT       NOT NULL REFERENCES member (id),
    -- TODO(D-08): 제목 길이 확정 시 조정. 검증은 PostPolicy 상수로 제한한다.
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ
);

CREATE INDEX idx_post_member_id ON post (member_id);
CREATE INDEX idx_post_created_at ON post (created_at DESC, id DESC);

CREATE TABLE post_url
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT  NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    url        TEXT    NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE INDEX idx_post_url_post_id ON post_url (post_id);

CREATE TABLE post_hashtag
(
    hashtag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT      NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    tag_name   VARCHAR(50) NOT NULL,
    CONSTRAINT uk_post_hashtag_post_tag UNIQUE (post_id, tag_name)
);

CREATE INDEX idx_post_hashtag_tag_name ON post_hashtag (tag_name);
